### ISSUE TITLE
MSA figures

### ISSUE THREAD

**Issue by kchennen** [CompEpigen/figeno#10]
Hi,
   Very nice and time saving tool. Is it also possible to do a Multiple Sequence Alignement (MSA) figure? I guess it would be a derivative of the  figure for alignments with BAM files?

Ex1: 
![](https://static.igem.wiki/teams/4495/wiki/images/modeling/image2.png)

Ex: 2: https://pypi.org/project/pyMSAviz/
![](https://pypi-camo.freetls.fastly.net/be9cbd7c21bc25f8f9bbe0668ada4a57c7b9325e/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d6f736869342f70794d534176697a2f6d61696e2f646f63732f696d616765732f6170695f6578616d706c6530332e706e67)

**Comment by e-sollier** [comment]
Hi,

Unfortunately, figeno does not support MSA, and I currently have no plan to implement it. I hope the way I wrote FIGENO: FIGure GENerator for GENOmics as a MSA in the readme is not too misleading.
The main problem is that figeno displays data along genomic coordinates, whereas in a MSA the sequences are aligned to each other, not to a reference genome, so this would not really fit with figeno. Also, the existing tool pyMSAviz that you show already looks very good and I don't know how I could improve upon it.

**Comment by kchennen** [comment]
OK. Thanks for the quick response
