### ISSUE TITLE
Input file for illustrating SV

### ISSUE THREAD

**Issue by priyambial123** [CompEpigen/figeno#11]
Thank for this tool. It works so smooth showing coverage, chromosomal position. Can you provide an example for the input vcf or tsv required to show structural variations

Priya

**Comment by e-sollier** [comment]
Hi,

There is an example vcf file here: https://github.com/CompEpigen/figeno/blob/main/test_data/THP1_SV.vcf . Any vcf produced by a SV caller should work. I've attached a zip file containing an example tsv file (it contains only the first SV of the vcf). The columns chr1, pos1, chr2, pos2 are required. strand1 and strand2 are optional and used to color the SV depending on the type. You can alternatively provide a "color" column which directly specifies the color of each SV.
[SV.zip](https://github.com/CompEpigen/figeno/files/15487785/SV.zip)

Does this answer your question?

**Comment by priyambial123** [comment]
Hi,
Thank you for the files. I will it confirm below with an example if I understood it right or not. Can you check
Is the example you have given is a translocation between chromosome 1 and 2?. 
So, if I have a deletion in chromosome 2, with start position as 12345 and end position as 23458. Is it represented like in the tsv fille:
```
chr2, pos1,   chr2, pos2
1       12345   1      23458
```

**Comment by e-sollier** [comment]
Yes, except that you wrote chr2 instead of chr1 in the first column, and the header should not contain commas; only tabs between columns.

**Comment by priyambial123** [comment]
I have the deletion in chromosome 2. So I gave it as chr2 in the first column. Can you explain why it should be chr1 here

Thank you

**Comment by e-sollier** [comment]
The header (first row) just gives the names of the columns. In the header, chr1 (resp. chr2) stands for the chromosome of the first (resp. second) end of the breakpoint. So there should always be chr1 and chr2 in the header, regardless of the actual chromosomes on which the breakpoint occurred.

**Comment by e-sollier** [comment]
I actually misread your previous comment. If the deletion occurred on chr2, then there should be "2" in the first and third column of the second row. But there should always be chr1 and chr2 in the header. In the example that I gave, both breakends were on chromosome 1.

**Comment by e-sollier** [comment]
Sor for your example it should be (with tabs between values):

```
chr1 pos1   chr2 pos2
2       12345   2      23458
```
