### ISSUE TITLE
chr

### ISSUE THREAD

**Issue by wangzhaohui-001** [CompEpigen/figeno#14]
Hello,
          My reference information is not like "chr_axis", so how to set ?
Thank you 1
![Uploading 微信图片_20240612100247.png…]()

**Comment by e-sollier** [comment]
Hi,

Sorry, I cannot open the image that you tried to upload and I don't understand your question. Could you please try to re-upload the image and reformulate your question?

**Comment by wangzhaohui-001** [comment]
My question is the reference genome of my research species chromosome name is not like "chr_axis". I want know i can use this tool.

**Comment by wangzhaohui-001** [comment]
My question is the reference genome of my research species chromosome name is not like "chr_axis". I want know  if i can use this tool.

**Comment by e-sollier** [comment]
I still don't really understand. Figeno should work with any reference genome. You will just need to provide a file for the genes annotation of your reference if you want to show genes, and a cytobands file if you want to show a chromosome ideogream. See: https://figeno.readthedocs.io/en/latest/content/describe_figure.html#general
