### ISSUE TITLE
Line height of the circos plot

### ISSUE THREAD

**Issue by ywzhang071394** [CompEpigen/figeno#19]
Hi,

Thank you for the nice tool. I recently used it and genrated a circos plot for CN+SV.
However, I found the lines for the short-range DEL and INS events (highlighted by the red arrow in the below figure) are too short that make many people overlook them. 
I wonder if there is any parameter for tuning it. Thank you!

![image](https://github.com/user-attachments/assets/1545386d-bf9e-418c-8979-41518e81f7b2)

**Comment by e-sollier** [comment]
Hi,

Thanks for your interest in figeno!
I've just added in version 1.4.6 a new parameter min_sv_height for the sv track: it's 0.1 by default and if you increase it (up to 1.0), it will result in a larger height for the SVs, in particular for the small ones. You can install the new version with `pip install figeno==1.4.6`.
Let me know if this is what you wanted, and if you have further ideas for improvements.

**Comment by ywzhang071394** [comment]
It works well! Thank you!
