### ISSUE TITLE
hope there is a option to demonstrate strand direction in the plot of bed files

### ISSUE THREAD

**Issue by YszSoleil** [CompEpigen/figeno#21]
Hi
As demonstrated, the bed file cannot show each interval's strand direction in the plot. Hope there is a option to set whether to demonstrate strand direction. An example is from IGV.
![image](https://github.com/user-attachments/assets/c451586c-f2ef-4641-89da-6cb6faf4db1c)
![image](https://github.com/user-attachments/assets/9fee9d29-718b-4741-b29b-b855706dda2f)
![image](https://github.com/user-attachments/assets/7dced386-ceb4-4897-974c-64cff0d7684d)

**Comment by e-sollier** [comment]
Hi,

Thanks for suggesting this feature! I have added support for displaying strand information in bed tracks in the latest update, that you can install with `pip install figeno==1.4.7`. This adds a "show_strand" option for the bed track. If you tick it, it will show arrows indicating the strand direction for each interval. This requires the strand information to be provided in the 6th column of the bed file. Please let me know if this is what you wanted.

Also, please note that, for now, all intervals from a bed file will be displayed on the same line, so there might be some overlaps. If this would be useful for you, I could potentially try to add support for splitting the overlapping intervals over multiple rows (like for the genes track).
