### ISSUE TITLE
Gene track

### ISSUE THREAD

**Issue by sighe** [CompEpigen/figeno#22]
Thank you for delivering the very useful tool. I wonder in what format of gene annotation files can be fed into figeno to show the gene track. 

I saw the YouTube movie and it guides the way to get a file from UCSC Table Browser. I succeeded in getting an output using the gene annotation file from the Table Browser as .txt, but have not managed to do so using a gff3 file I obtained from Braker3 that I ran by myself.

I would really appreciate your guidance about how to proceed or to what I should refer.

Best,

sighe

**Comment by e-sollier** [comment]
Hello,

Thanks for your interest in figeno! The gff3 format is supported by figeno, it should be automatically recognized if the filename endswith ".gff3" or ".gff3.gz". If it does not work, could you please share with me the error message that you get, as well as the gff3 file that you used?

**Comment by e-sollier** [comment]
Solved via email: there was a problem in the parsing of gff3 files, which is now fixed in version 1.5.0.
