### ISSUE TITLE
ASE track

### ISSUE THREAD

**Issue by Lijingtangbo** [CompEpigen/figeno#5]
Hi, I met problem for ASE track. It appears for one gene but not for another even though I used the same input files and verified SNPs in both VCF and ASEcounts files. Do you have any thoughts on that?

Thanks.

**Comment by e-sollier** [comment]
Hi,

Could you please share the error message, as well as which version of figeno you were using ?

**Comment by Lijingtangbo** [comment]
I used 1.0.8. Actually, there is no error message. The plot was wrote out with the ASE track blank and others tracks are correct. I used the same input files for plotting a region encompassing gene (PEG10) and plotting a region containing gene (MEG3). The plot for PEG10 is fine, but the plot for MEG3 is not. I verified I have informative SNPs in VCF and ASEreadcounter files for both regions with min-depth > 6.

**Comment by e-sollier** [comment]
This is strange, if the plot is empty it should mean that there were no SNPs in the region in the ASEReadcounter file.
Would you be able to share your input files and config file so that I can try to understand what happened ?

**Comment by Lijingtangbo** [comment]
Sure. Here I sent you the ASEReadcounter file and two config files. The Peg10 plot is fine but not for Meg3.
[Meg3_test.json](https://github.com/CompEpigen/figeno/files/15126209/Meg3_test.json)
[Peg10_test.json](https://github.com/CompEpigen/figeno/files/15126211/Peg10_test.json)
[ASEReadcounter.test.txt.gz](https://github.com/CompEpigen/figeno/files/15126265/ASEReadcounter.test.txt.gz)

**Comment by e-sollier** [comment]
Thanks.

Apparently the gene annotations for Meg3 are incomplete in the reference ARS-UCD1.2, so figeno assumed it is not a protein coding gene. 
In order to see Meg3 in the genes track, you should set "only_protein_coding": false.
I updated the ase track to always show SNPs even if they are in non protein coding genes. If you download the version 1.1.0 this should work.

**Comment by Lijingtangbo** [comment]
Thank you very much! 1.1.0 is working.

Indeed the Meg3 is a lncRNA. Actually, since I worked with imprinting gene clusters. All clusters contain lncRNAs that expressed allelic bias. If would be great if you could include phasing feature in ASE track in the future.
