### ISSUE TITLE
basemod_freq

### ISSUE THREAD

**Issue by JoKo95** [CompEpigen/figeno#6]
Hi!

I wanted to create a basemod_freq track to plot my RNA methylation data.
My input file is a tab-separated 3-column file as recommended.
The RNA methylation sites are not continuous. I have several methylation sites per transcript only.
However, I am receiving the attached error.
Figeno is looking for a .tbi file, but do I really need that for my purpose?

I am using the Windows GUI (version v1.0).

![error](https://github.com/CompEpigen/figeno/assets/168171762/42e35fac-9b2b-40be-ab7f-59a4e52bbf0e)

**Comment by e-sollier** [comment]
Ah sorry, bad timing! I've only added support for 3-column tsv file for the basemod_freq track in version 1.1.0, which I've just now released, but I (quite stupidly) had already updated the documentation 2 days ago. So if you install the new version, this should now work and not complain about a missing index.
In version 1.1.0 I have also added a "style" parameter for the basemod_freq track, which if you set to "dots" might result in a better-looking figure if you have sparse data.

**Comment by JoKo95** [comment]
Yes, with the new version I could plot it - Thanks a lot!

Do you plan to implement the possibility to plot the modification sites as bars?
I tried "lines" and "dots" styles, but I think that bars would look even prettier for sparse data.

Best wishes!

**Comment by e-sollier** [comment]
I've just made a quick implementation of a "bars" style. You can download this version from: https://drive.google.com/drive/folders/1u6T0GFcICt9EDKZaMBcvUaCqmrGY_t9w?usp=sharing (in case your browser does not let you download the files from ggdrive, try with a different web browser).
You can adjust the bar widths with the linewidth parameter.

Is this what you want, or did you have something else in mind ?
